spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  # Configuração do serviço de email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:seu-email@gmail.com}
    password: ${EMAIL_PASSWORD:sua-senha}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

# Configuração com mensageria desabilitada
app:
  messaging:
    enabled: false
 